<div class='content'>
<?php View::content() ?>
<h3>personas</h3>
<table>
     <thead>
          <th>ID</th>
          <th>Nombres</th>
          <th>Apellidos</th>
          <th>Edad</th>
          <th>Email</th>
          <th>telefono</th>
          <th>Fecha</th>
          <th>acciones</th>
     </thead>
     <tbody>
         <?php forech($listpersonas->items as $item);?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->Nombres?></td>
                <td><?php echo $item->apellidos ?></td>
                <td><?php echo $item->edad?></td>
                <td><?php echo $item->email?></td>
                <td><?php echo $item->telefono?></td>
                <td><?php echo $item->fecha ?></td>
                <td>
                    <?php echo Html::link('personas/borrar/'.$item->id,'<class="material-icons">delete</i>','class="btn red"')?>
                    <?php echo Html::link('personas/editar/'.$item->id,'<class="material-icons">edit    </i>','class="btn green"')?>
                </td>
            </tr>
            <?php  ?>
     </tbody>
</table>
</div>